### PR TITLE
construct the DOM with createElement instead of jquery.append, fix #29 

### LINKED ISSUE #29: construct the DOM with createElement instead of jquery.append
Got from FIrefox addon review

```
This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk. For more information, see https://developer.mozilla.org/en/XUL_School/DOM_Building_and_HTML_Insertion . Here are some examples that were discovered:
popup/index.js#192 and others
```

In popup/index.js we use $.append to render html, which is unsafe.

We should remove jquery.append and construct the DOM with createElement instead
https://github.com/gitcoinco/chrome_ext/blob/master/src/script/popup/index.js#L192

### PR DESCRIPTION
**Pull request by gasolin**
to meet firefox's review request, need to remove $.append and use dom createElement instead

### CODE REVIEW

**Comment by gasolin** [comment]
@owocki @jclancy93 could you help review this?

**Comment by owocki** [comment]
i did not test... but the code looks sane (at least, as sane as raw javascript is) to me.

have you regression tested this?

**Comment by gasolin** [comment]
test on chrome and it behave the same as 0.904

**Comment by gasolin** [comment]
updated to latest branch, @owocki  could you take a look again?

**Comment by owocki** [comment]
didnt test, but LGTM.  

@gasolin great seeing these PRs coming in from you.  id be happy to add you as a maintainer for this repo if its something youre interested in.

**Comment by gasolin** [comment]
@owocki  Thanks, I'm glad to help :)

**Pull request merged**
