### PR TITLE
WIP - Enable to run chrome_ext as Firefox extension, fix #1

### LINKED ISSUE #1: provide Firefox version
Firefox now provide web extension API which is similar to Chrome
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

And MetaMask already provided the Firefox extension 
https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/?src=api

### PR DESCRIPTION
**Pull request by gasolin**
the PR moved extension to the src/ folder, add npm package file and script to update dependency libraries (jquery.js and webextension browser-polyfill.js)

Developer could update depend on libraries and build with npm scripts

```
npm install
npm run build
```

Or find extension lint information with 

```
npm run lint
```

The patch moved `chrome.extension` API to `browser.runtime` API and polyfilled with `browser-polyfill.js`

### CODE REVIEW

**Comment by owocki** [comment]
nice!  will test as soon as https://addons.mozilla.org/en-US/firefox/addon/gitcoin/ is live

**Comment by gasolin** [comment]
@owocki I update `0.12` which moved the code injection part to background (instead of doing in content script) and reduce the addon site to 450k by removed `promo` images. Please try it again.

**Comment by owocki** [comment]
trying now

**Comment by owocki** [comment]
code looks good.  extension seems to build as promised.

did you regression-test this against chrome to see if it still works there too?

**Comment by gasolin** [comment]
yes, load `src/` into `chrome://extensions/` works fine as well

**Comment by owocki** [comment]
@rafaelfragoso left u a message about this on slack

**Comment by gasolin** [comment]
I found a major regression for this PR due to removed innerHTML & use extension API instead.
The injected `respond_to_ext` seems not work properly. 

I'd separate the patch and try to land the architecture part (move extension into src/ folder and add the lint script), then come back to fix the extension

**Comment by owocki** [comment]
uh oh.. a bunch of merge conflicts here now

**Comment by gasolin** [comment]
deprecated the WIP

**Pull request closed without merging**
