### PR TITLE
https://github.com/gitcoinco/chrome_ext/issues/17 : purple for closed…

### PR DESCRIPTION
**Pull request by karsiwek**
…, blue for claimed, regular (green) for open

tried to be bit consistent with github - "merged" button is purple so I thought "fullfilled" should also be.

also had to remove idx_status=open from query becouse otherwise we won't get any data other than "open"

### CODE REVIEW

**Comment by owocki** [comment]
> also had to remove idx_status=open from query becouse otherwise we won't get any data other than "open"

my concern about this is that we'll get non-open bounties in the extension up top... is that something we want to do??   i think if we do this then we should have a status column in the table

**Comment by owocki** [comment]
> var status_to_color

this is awesome!  thanks for the pR!

**Comment by karsiwek** [comment]
yes, i've been thinking about having not open bounties, but:
1. all fullfilled bounties are not on the issues screen anyway (because they're on "closed issues" tab)
2. claimed issues might still be on the issues screen - just for information - someone can change their mind anyway :)
anyway - if we call only for open bounties, we don't need colors :)

If you're worried about performance (at some point most of the bounties would be closed so we'll process a lot of unnecessary data) i'm working now on a improvement. You can wait with this PR until my second one, so you can see what i mean :)

**Comment by owocki** [comment]
thanks for the thoughtful comment.. id be willing to just merge what you've done now if there was a status field on this table.. http://bits.owocki.com/2N27251O2X1B/Screen%20Shot%202018-01-12%20at%209.37.17%20AM.png

**Comment by karsiwek** [comment]
done

**Pull request merged**
